import { TeamLabStructureSpec } from '../types/teamLabTypes';

export const TEAM_LAB_STRUCTURE_SPEC: TeamLabStructureSpec = {
  version: '3.0',
  paths: [
    // .github layer
    { path: '.github', type: 'directory', required: true },
    {
      path: '.github/copilot-instructions.md',
      type: 'file',
      required: true,
      ownership: 'seeded',
      templateId: 'copilot-instructions',
      protected: true,
    },
    { path: '.github/instructions', type: 'directory', required: true },
    {
      path: '.github/instructions/semantic-layer.instructions.md',
      type: 'file',
      required: true,
      ownership: 'seeded',
      templateId: 'semantic-layer-instructions',
      protected: true,
    },
    {
      path: '.github/instructions/modeling.instructions.md',
      type: 'file',
      required: true,
      ownership: 'seeded',
      templateId: 'modeling-instructions',
      protected: true,
    },
    {
      path: '.github/instructions/testing.instructions.md',
      type: 'file',
      required: true,
      ownership: 'seeded',
      templateId: 'testing-instructions',
      protected: true,
    },
    {
      path: '.github/instructions/documentation.instructions.md',
      type: 'file',
      required: true,
      ownership: 'seeded',
      templateId: 'documentation-instructions',
      protected: true,
    },
    {
      path: '.github/instructions/governance.instructions.md',
      type: 'file',
      required: true,
      ownership: 'seeded',
      templateId: 'governance-instructions',
      protected: true,
    },
    { path: '.github/agents', type: 'directory', required: true },
    {
      path: '.github/agents/concierge.agent.md',
      type: 'file',
      required: true,
      ownership: 'seeded',
      templateId: 'concierge-agent',
      protected: true,
    },
    {
      path: '.github/agents/task-designer.agent.md',
      type: 'file',
      required: true,
      ownership: 'seeded',
      templateId: 'task-designer-agent',
      protected: true,
    },
    {
      path: '.github/agents/agent-builder.agent.md',
      type: 'file',
      required: true,
      ownership: 'seeded',
      templateId: 'agent-builder-agent',
      protected: true,
    },
    {
      path: '.github/agents/skill-builder.agent.md',
      type: 'file',
      required: true,
      ownership: 'seeded',
      templateId: 'skill-builder-agent',
      protected: true,
    },
    { path: '.github/skills', type: 'directory', required: true },
    { path: '.github/skills/build-context', type: 'directory', required: true },
    {
      path: '.github/skills/build-context/SKILL.md',
      type: 'file',
      required: true,
      ownership: 'seeded',
      templateId: 'skill-build-context',
      protected: true,
    },
    { path: '.github/skills/analyze-model', type: 'directory', required: true },
    {
      path: '.github/skills/analyze-model/SKILL.md',
      type: 'file',
      required: true,
      ownership: 'seeded',
      templateId: 'skill-analyze-model',
      protected: true,
    },
    { path: '.github/skills/plan-model-update', type: 'directory', required: true },
    {
      path: '.github/skills/plan-model-update/SKILL.md',
      type: 'file',
      required: true,
      ownership: 'seeded',
      templateId: 'skill-plan-model-update',
      protected: true,
    },

    // ai_context layer
    { path: 'ai_context', type: 'directory', required: true },
    {
      path: 'ai_context/project_index.json',
      type: 'file',
      required: true,
      ownership: 'generated',
      templateId: 'project-index',
    },
    {
      path: 'ai_context/workspace_summary.md',
      type: 'file',
      required: true,
      ownership: 'generated',
      templateId: 'workspace-summary',
    },
    {
      path: 'ai_context/team_lab_manifest.json',
      type: 'file',
      required: true,
      ownership: 'generated',
      templateId: 'team-lab-manifest',
    },
    {
      path: 'ai_context/repo_baseline.md',
      type: 'file',
      required: true,
      ownership: 'human-required',
      templateId: 'repo-baseline',
      protected: true,
    },
  ],
};
