import * as crypto from 'crypto';
import { ContextDocument, ContextDocumentType, ContextStoreService } from '../core/types';
import { WorkspaceService } from '../core/types';

const CONTEXT_DIR = '.team_lab/context';
const HEADER_PREFIX = '<!-- team-lab ';
const HEADER_SUFFIX = ' -->';

// ─── Header format ────────────────────────────────────────────────────────────
//
// Each context document is stored as a markdown file with a single-line JSON
// header at the top:
//
//   <!-- team-lab {"id":"<uuid>","type":"<type>","generatedAt":"<iso>"} -->
//
//   # Document Title
//   ...content...
//
// The header is machine-readable and human-ignorable.

interface ContextHeader {
  id: string;
  type: ContextDocumentType;
  generatedAt: string;
}

export class ContextStoreServiceImpl implements ContextStoreService {
  constructor(private readonly workspace: WorkspaceService) {}

  async write(type: ContextDocumentType, content: string): Promise<ContextDocument> {
    const doc: ContextDocument = {
      id: crypto.randomUUID(),
      type,
      generatedAt: new Date(),
      content,
    };

    const header: ContextHeader = {
      id: doc.id,
      type: doc.type,
      generatedAt: doc.generatedAt.toISOString(),
    };

    const fileContent =
      `${HEADER_PREFIX}${JSON.stringify(header)}${HEADER_SUFFIX}\n\n${content}`;

    await this.workspace.writeFile(this.filePath(type), fileContent);
    return doc;
  }

  async read(type: ContextDocumentType): Promise<ContextDocument | null> {
    const path = this.filePath(type);
    const exists = await this.workspace.fileExists(path);
    if (!exists) {return null;}

    try {
      const raw = await this.workspace.readFile(path);
      return this.parse(raw);
    } catch {
      return null;
    }
  }

  async readAll(): Promise<ContextDocument[]> {
    const types: ContextDocumentType[] = [
      'architecture',
      'naming_conventions',
      'source_index',
      'pattern_library',
      'governance_index',
      'product_catalog',
    ];

    const results = await Promise.all(types.map(t => this.read(t)));
    return results.filter((d): d is ContextDocument => d !== null);
  }

  async isStale(type: ContextDocumentType, thresholdHours = 24): Promise<boolean> {
    const doc = await this.read(type);
    if (!doc) {return true;}

    const ageMs = Date.now() - doc.generatedAt.getTime();
    const thresholdMs = thresholdHours * 60 * 60 * 1000;
    return ageMs > thresholdMs;
  }

  async getAvailableTypes(): Promise<ContextDocumentType[]> {
    const docs = await this.readAll();
    return docs.map(d => d.type);
  }

  // ─── Private helpers ────────────────────────────────────────────────────────

  private filePath(type: ContextDocumentType): string {
    return `${CONTEXT_DIR}/${type}.md`;
  }

  private parse(raw: string): ContextDocument | null {
    const firstLine = raw.split('\n')[0];
    if (!firstLine.startsWith(HEADER_PREFIX)) {return null;}

    const jsonStr = firstLine.slice(HEADER_PREFIX.length, -HEADER_SUFFIX.length);
    const header = JSON.parse(jsonStr) as ContextHeader;

    // Content is everything after the header line and the blank line
    const content = raw.split('\n').slice(2).join('\n');

    return {
      id: header.id,
      type: header.type,
      generatedAt: new Date(header.generatedAt),
      content,
    };
  }
}

// ─── Provenance comment block ─────────────────────────────────────────────────
//
// Appended to the top of any file generated using context documents.

export function buildProvenanceBlock(docs: ContextDocument[]): string {
  if (!docs.length) {return '';}

  const lines = [
    '# Generated by Team Lab',
    `# generated: ${new Date().toISOString()}`,
    '# context:',
    ...docs.map(d => `#   ${d.type}: ${d.id}`),
    '',
  ];

  return lines.join('\n');
}
