import { TeamLabTemplateProvider, TeamLabTemplateContext } from '../types/teamLabTypes';

export class TeamLabTemplates implements TeamLabTemplateProvider {
  render(templateId: string, context: TeamLabTemplateContext): string {
    switch (templateId) {
      case 'copilot-instructions':
        return `# Team Lab Repository Instructions

This repository uses Team Lab conventions for dbt-oriented development.

## Chat-First Operating Model
- Use GitHub Copilot Chat as the primary interaction surface
- The Concierge agent (\`.github/agents/concierge.agent.md\`) is the default Team Lab entry point
- The Task Designer agent refines vague requests into precise implementation tasks
- Skills under \`.github/skills/\` provide reusable capabilities

## Working Expectations
- Read \`ai_context/repo_baseline.md\` before performing any task
- Prefer clear, maintainable SQL and repository-aware changes
- Follow existing naming and folder conventions
- Favor simple, working solutions over unnecessary complexity
- Review scoped instructions under \`.github/instructions/\` for domain-specific guidance

Generated at: ${context.generatedAt}
`;

      case 'semantic-layer-instructions':
        return `# Semantic Layer Instructions

## Purpose
Guide semantic-layer work in this repository.

## Guidelines
- Confirm model grain before proposing changes
- Prefer repo-consistent patterns
- Review existing semantic assets before creating new ones
`;

      case 'modeling-instructions':
        return `# Modeling Instructions

## Purpose
Guide dbt model development.

## Guidelines
- Prefer clear CTE-based SQL
- Follow existing naming and folder conventions
- Avoid introducing unexplained new patterns
`;

      case 'testing-instructions':
        return `# Testing Instructions

## Purpose
Guide testing-related changes.

## Guidelines
- Review existing dbt tests before adding new ones
- Prefer targeted tests that match model intent
- Keep test logic aligned to current repo patterns
`;

      case 'documentation-instructions':
        return `# Documentation Instructions

## Purpose
Guide documentation work.

## Guidelines
- Keep docs aligned to implemented behavior
- Prefer concise, accurate descriptions
- Avoid speculative documentation
`;

      case 'governance-instructions':
        return `# Governance Instructions

## Purpose
Guide governance-related changes.

## Guidelines
- Respect naming and structural conventions
- Surface assumptions clearly
- Avoid policy drift without evidence
`;

      case 'workspace-summary':
        return `# Workspace Summary

Workspace: ${context.workspaceName}

This file is generated by Team Lab.
Generated at: ${context.generatedAt}
`;

      case 'project-index':
        return `{
  "generatedAt": "${context.generatedAt}",
  "projects": []
}
`;

      case 'team-lab-manifest':
        return `{
  "version": "2.0",
  "generatedAt": "${context.generatedAt}",
  "files": {
    "generated": [],
    "seeded": [],
    "human_required": []
  }
}
`;

      case 'repo-baseline':
        return `# Repository Baseline

<!-- TEAM_LAB_BASELINE_TEMPLATE -->

## Purpose of This File
This file provides a human-verified description of the repository.
It acts as a baseline for AI agents to confirm they understand the structure and intent correctly.

Agents must read this file before performing any task.

---

## Repository Overview
Describe the purpose of this repository in 2\u20135 sentences.

Example:
This repository contains dbt projects used for ingestion, transformation, semantic modeling, and analytics support.

---

## dbt Projects

List all dbt projects and their roles.

### Project 1
- Name:
- Path:
- Purpose:

### Project 2
- Name:
- Path:
- Purpose:

(Add more as needed)

---

## High-Level Architecture

Describe how the main parts of the repo relate to each other.

Example:
- \`pipeline\` handles ingestion and staging
- \`core\` handles transformations
- \`semantic\` contains semantic-layer assets and reporting-facing models

---

## Key Conventions

List important rules agents should follow.

Examples:
- Prefer CTEs over nested subqueries
- Use snake_case naming
- Follow existing dbt folder conventions
- Avoid introducing new patterns without evidence from the repo

---

## Known Constraints

Anything important agents should not assume.

Examples:
- Not all projects are active
- Some models are experimental
- Incremental logic varies by domain
- Semantic assets may live in only one project

---

## Notes for AI Agents

Anything helpful for validating correctness.

Examples:
- Confirm model grain before adding joins
- Check upstream staging models before changing business logic
- Use existing naming patterns before proposing new ones
`;

      case 'concierge-agent':
        return `# Concierge Agent

## Role
Act as the front door and coordinating agent for Team Lab.

## Responsibilities
- Review context before acting
- Read \`repo_baseline.md\` first when present
- Route work to the right agent or skill
- Break work into manageable steps
- Keep work aligned to repo conventions

## Persona
Senior data engineer, dbt expert, SQL expert, technical coordinator.

## Required Context Review
1. Read \`ai_context/repo_baseline.md\`
2. Review \`ai_context/project_index.json\`
3. Check relevant files under \`ai_context/\`
4. Respect \`.github/copilot-instructions.md\` and scoped instructions

## Expected Inputs
- Natural language task descriptions
- References to specific models, sources, or domains

## Expected Outputs
- Delegated subtasks with clear scope
- Coordination summaries
- Status updates

## Constraints
- Do not invent missing facts
- State assumptions clearly
- Prefer simple, working solutions
- Do not proceed without a completed repo baseline
`;

      case 'prompt-engineer-agent':
        return `# Prompt Engineer Agent

## Role
Translate natural language requests into precise, context-aware implementation tasks.

## Responsibilities
- Review context before acting
- Read \`repo_baseline.md\` first when present
- Clarify joins, columns, grain, assumptions, and impact
- Structure requests for downstream agents
- Improve prompts and task definitions

## Required Context Review
1. Read \`ai_context/repo_baseline.md\`
2. Review relevant context documents
3. Respect scoped instructions

## Expected Inputs
- Unstructured change requests
- Vague or incomplete task descriptions

## Expected Outputs
- Structured, precise implementation prompts
- Clarifying questions when needed
- Impact assessments

## Constraints
- Do not invent missing facts
- State assumptions clearly
- Prefer repo-aware prompts
`;

      case 'agent-builder-agent':
        return `# Agent Builder Agent

## Role
Create and refine Team Lab agent definitions.

## Responsibilities
- Review context before acting
- Read \`repo_baseline.md\` first when present
- Create or refine \`.agent.md\` files
- Define responsibilities, constraints, inputs, and outputs
- Propose new agents when repeated workflows justify them

## Required Context Review
1. Read \`ai_context/repo_baseline.md\`
2. Review existing agents in \`.github/agents/\`
3. Respect repo conventions

## Expected Inputs
- Descriptions of repeated workflows or capability gaps
- Existing agent files needing refinement

## Expected Outputs
- New or updated \`.agent.md\` files
- Agent responsibility definitions

## Constraints
- Do not create agents for one-off tasks
- Keep agent scope focused and clear
- Follow existing agent structure patterns
`;

      case 'skill-builder-agent':
        return `# Skill Builder Agent

## Role
Create and refine Team Lab skill definitions.

## Responsibilities
- Review context before acting
- Read \`repo_baseline.md\` first when present
- Create or refine skill folders and \`SKILL.md\`
- Identify repeatable capabilities that should become skills
- Define when skills should be used and what they require

## Required Context Review
1. Read \`ai_context/repo_baseline.md\`
2. Review existing skills in \`.github/skills/\`
3. Respect repo conventions

## Expected Inputs
- Descriptions of repeatable tasks
- Existing skill definitions needing refinement

## Expected Outputs
- New or updated skill folders with \`SKILL.md\`
- Skill usage documentation

## Constraints
- Do not create skills for non-repeatable tasks
- Keep skill scope focused
- Follow existing skill structure patterns
`;

      case 'skill-build-context':
        return `# Build Context

## Purpose
Generate or refresh AI context documents for the repository.

## When to Use
- After significant project structure changes
- When context documents are missing or stale
- When onboarding a new project into Team Lab

## Inputs
- Workspace root path
- Detected dbt projects from \`ai_context/project_index.json\`

## Outputs
- Updated \`ai_context/workspace_summary.md\`
- Updated \`ai_context/project_index.json\`
- Updated \`ai_context/team_lab_manifest.json\`

## Steps
1. Scan workspace for dbt projects (\`dbt_project.yml\`)
2. Read project configurations
3. Generate workspace summary
4. Update project index
5. Update manifest with timestamps

## Constraints
- Do not overwrite \`repo_baseline.md\`
- Do not modify seeded agent or instruction files
- Only update generated files
`;

      case 'skill-analyze-model':
        return `# Analyze Model

## Purpose
Analyze a dbt model to understand its structure, dependencies, and purpose.

## When to Use
- Before making changes to a model
- When understanding model grain, joins, or dependencies
- When reviewing model quality or patterns

## Inputs
- Path to a dbt model SQL file
- Repo baseline context from \`ai_context/repo_baseline.md\`
- Project context from \`ai_context/project_index.json\`

## Outputs
- Model summary (grain, purpose, key columns)
- Upstream dependencies (refs, sources)
- Downstream dependents
- Observations or potential issues

## Steps
1. Read the model SQL
2. Parse refs and sources
3. Check YAML schema file for column documentation
4. Summarize structure and intent
5. Identify patterns and concerns

## Constraints
- Do not modify any files
- State assumptions clearly
- Use existing repo patterns as reference
`;

      case 'skill-plan-model-update':
        return `# Plan Model Update

## Purpose
Create a structured plan for updating a dbt model based on a natural language request.

## When to Use
- When a developer describes a change they want to make
- Before executing a model update
- When coordinating complex model changes

## Inputs
- Path to the target dbt model
- Natural language description of the desired change
- Repo baseline context
- Model analysis (from Analyze Model skill)

## Outputs
- Step-by-step implementation plan
- Affected columns and joins
- Upstream/downstream impact assessment
- Assumptions and risks

## Steps
1. Analyze the current model (invoke Analyze Model)
2. Parse the user request into specific changes
3. Identify affected columns, CTEs, and joins
4. Assess upstream and downstream impact
5. Produce a structured plan

## Constraints
- Do not modify any files
- Clearly separate facts from assumptions
- Flag any ambiguity in the request
- Prefer minimal changes that achieve the goal
`;

      default:
        return '';
    }
  }
}
