import { TeamLabTemplateProvider, TeamLabTemplateContext } from '../types/teamLabTypes';

export class TeamLabTemplates implements TeamLabTemplateProvider {
  render(templateId: string, context: TeamLabTemplateContext): string {
    switch (templateId) {
      case 'copilot-instructions':
        return `# Team Lab Repository Instructions

This repository uses Team Lab conventions for dbt-oriented development.
Prefer clear, maintainable SQL and repository-aware changes.
Generated at: ${context.generatedAt}
`;

      case 'semantic-layer-instructions':
        return `# Semantic Layer Instructions

## Purpose
Guide semantic-layer work in this repository.

## Guidelines
- Confirm model grain before proposing changes
- Prefer repo-consistent patterns
- Review existing semantic assets before creating new ones
`;

      case 'modeling-instructions':
        return `# Modeling Instructions

## Purpose
Guide dbt model development.

## Guidelines
- Prefer clear CTE-based SQL
- Follow existing naming and folder conventions
- Avoid introducing unexplained new patterns
`;

      case 'testing-instructions':
        return `# Testing Instructions

## Purpose
Guide testing-related changes.

## Guidelines
- Review existing dbt tests before adding new ones
- Prefer targeted tests that match model intent
- Keep test logic aligned to current repo patterns
`;

      case 'documentation-instructions':
        return `# Documentation Instructions

## Purpose
Guide documentation work.

## Guidelines
- Keep docs aligned to implemented behavior
- Prefer concise, accurate descriptions
- Avoid speculative documentation
`;

      case 'governance-instructions':
        return `# Governance Instructions

## Purpose
Guide governance-related changes.

## Guidelines
- Respect naming and structural conventions
- Surface assumptions clearly
- Avoid policy drift without evidence
`;

      case 'workspace-summary':
        return `# Workspace Summary

Workspace: ${context.workspaceName}

This file is generated by Team Lab.
Generated at: ${context.generatedAt}
`;

      case 'project-index':
        return `{
  "generatedAt": "${context.generatedAt}",
  "projects": []
}
`;

      case 'team-lab-manifest':
        return `{
  "version": "2.0",
  "generatedAt": "${context.generatedAt}",
  "files": {
    "generated": [],
    "seeded": [],
    "human_required": []
  }
}
`;

      case 'repo-baseline':
        return `# Repository Baseline

<!-- TEAM_LAB_BASELINE_TEMPLATE -->

## Purpose of This File
This file provides a human-verified description of the repository.
It acts as a baseline for AI agents to confirm they understand the structure and intent correctly.

Agents must read this file before performing any task.

---

## Repository Overview
Describe the purpose of this repository in 2\u20135 sentences.

Example:
This repository contains dbt projects used for ingestion, transformation, semantic modeling, and analytics support.

---

## dbt Projects

List all dbt projects and their roles.

### Project 1
- Name:
- Path:
- Purpose:

### Project 2
- Name:
- Path:
- Purpose:

(Add more as needed)

---

## High-Level Architecture

Describe how the main parts of the repo relate to each other.

Example:
- \`pipeline\` handles ingestion and staging
- \`core\` handles transformations
- \`semantic\` contains semantic-layer assets and reporting-facing models

---

## Key Conventions

List important rules agents should follow.

Examples:
- Prefer CTEs over nested subqueries
- Use snake_case naming
- Follow existing dbt folder conventions
- Avoid introducing new patterns without evidence from the repo

---

## Known Constraints

Anything important agents should not assume.

Examples:
- Not all projects are active
- Some models are experimental
- Incremental logic varies by domain
- Semantic assets may live in only one project

---

## Notes for AI Agents

Anything helpful for validating correctness.

Examples:
- Confirm model grain before adding joins
- Check upstream staging models before changing business logic
- Use existing naming patterns before proposing new ones
`;

      case 'orchestrator-agent':
        return `# Orchestrator Agent

## Role
Act as the front door and coordinating agent for Team Lab.

## Responsibilities
- Review context before acting
- Read \`repo_baseline.md\` first when present
- Route work to the right agent or skill
- Break work into manageable steps
- Keep work aligned to repo conventions

## Persona
Senior data engineer, dbt expert, SQL expert, technical coordinator.

## Required Context Review
1. Read \`ai_context/repo_baseline.md\`
2. Review \`ai_context/project_index.json\`
3. Check relevant files under \`ai_context/\`
4. Respect \`.github/copilot-instructions.md\` and scoped instructions

## Expected Inputs
- Natural language task descriptions
- References to specific models, sources, or domains

## Expected Outputs
- Delegated subtasks with clear scope
- Coordination summaries
- Status updates

## Constraints
- Do not invent missing facts
- State assumptions clearly
- Prefer simple, working solutions
- Do not proceed without a completed repo baseline
`;

      case 'prompt-engineer-agent':
        return `# Prompt Engineer Agent

## Role
Translate natural language requests into precise, context-aware implementation tasks.

## Responsibilities
- Review context before acting
- Read \`repo_baseline.md\` first when present
- Clarify joins, columns, grain, assumptions, and impact
- Structure requests for downstream agents
- Improve prompts and task definitions

## Required Context Review
1. Read \`ai_context/repo_baseline.md\`
2. Review relevant context documents
3. Respect scoped instructions

## Expected Inputs
- Unstructured change requests
- Vague or incomplete task descriptions

## Expected Outputs
- Structured, precise implementation prompts
- Clarifying questions when needed
- Impact assessments

## Constraints
- Do not invent missing facts
- State assumptions clearly
- Prefer repo-aware prompts
`;

      case 'agent-builder-agent':
        return `# Agent Builder Agent

## Role
Create and refine Team Lab agent definitions.

## Responsibilities
- Review context before acting
- Read \`repo_baseline.md\` first when present
- Create or refine \`.agent.md\` files
- Define responsibilities, constraints, inputs, and outputs
- Propose new agents when repeated workflows justify them

## Required Context Review
1. Read \`ai_context/repo_baseline.md\`
2. Review existing agents in \`.github/agents/\`
3. Respect repo conventions

## Expected Inputs
- Descriptions of repeated workflows or capability gaps
- Existing agent files needing refinement

## Expected Outputs
- New or updated \`.agent.md\` files
- Agent responsibility definitions

## Constraints
- Do not create agents for one-off tasks
- Keep agent scope focused and clear
- Follow existing agent structure patterns
`;

      case 'skill-builder-agent':
        return `# Skill Builder Agent

## Role
Create and refine Team Lab skill definitions.

## Responsibilities
- Review context before acting
- Read \`repo_baseline.md\` first when present
- Create or refine skill folders and \`SKILL.md\`
- Identify repeatable capabilities that should become skills
- Define when skills should be used and what they require

## Required Context Review
1. Read \`ai_context/repo_baseline.md\`
2. Review existing skills in \`.github/skills/\`
3. Respect repo conventions

## Expected Inputs
- Descriptions of repeatable tasks
- Existing skill definitions needing refinement

## Expected Outputs
- New or updated skill folders with \`SKILL.md\`
- Skill usage documentation

## Constraints
- Do not create skills for non-repeatable tasks
- Keep skill scope focused
- Follow existing skill structure patterns
`;

      default:
        return '';
    }
  }
}
